### ISSUE TITLE
Not an Issue but just if you have time for a suggestion

### ISSUE THREAD

**Issue by developer9969** [damienaicheh/BundletoolHelperExample#1]
HI there,

Your tutorials helped me a lot and I managed to setup pipeline quite easily thanks to your tutorials.
I am trying to use your bundle tool helper to get apk from aab and send to appcenter and I am getting an error and not sure why.

**'D:\a\1\s\mycompany.keystore' was not found.**

This is weird because the secure file Task is successful, but the AabConvertToUniversalApk is saying it cannot find it.
Am I missing the obvious?

Any suggestions or pointers?      
	   

   **We dont use github but azure repo so left it blank. Not sure if the problem**

   - task: InstallBundletool@1
            inputs:
              username: ''
              personalAccessToken: ''

      - task: DownloadPipelineArtifact@2
            displayName: 'Downloading aab package'
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              itemPattern: '**/mycompany-Signed.aab'
              targetPath: '$(System.ArtifactsDirectory)\drop'
              
              
          - task: AabConvertToUniversalApk@1
            inputs:
                  aabFilePath: '$(System.ArtifactsDirectory)\drop\mycompany-Signed.aab'
                  keystoreFilePath: $(keystore.filename)
                  keystorePassword: $(keystore.password)
                  keystoreAlias: $(key.alias)
                  keystoreAliasPassword: $(key.password)
                  outputFolder: '$(System.ArtifactsDirectory)\drop'
				  
				  
				  bundletoolJarPath : Did not know what to put in here is it needed

**Comment by damienaicheh** [comment]
Hi,

It's easy to use, let me explain to you based on the example of this repos: `https://github.com/damienaicheh/BundletoolHelperExample/blob/master/azure-pipelines.yml`

When you use the task to install the keystore:
```
- task: DownloadSecureFile@1
  name: keyStore
  displayName: "Download keystore from secure files"
  inputs:
    secureFile: production.jks
```

you give it a name to your `production.jks` file, here it's `keystore`.

Then with this task you have the ability to get the path of your `production.jks` file directly like by using the `secureFilePath` property like this: `$(keyStore.secureFilePath)`

then you can use this like this:

```
- task: AabConvertToUniversalApk@1
  inputs:
    aabFilePath: '$(Build.SourcesDirectory)/XamarinAndroidAab/bin/$(buildConfiguration)/*.aab'
    keystoreFilePath: '$(keyStore.secureFilePath)' # => This is the variable I just explained
    keystorePassword: '$(keystore.password)' # => the folowing variables comes from a variable group in the secure storage.
    keystoreAlias: '$(key.alias)'
    keystoreAliasPassword: '$(key.password)'
    outputFolder: '$(Build.SourcesDirectory)/tmp'
```

Finaly as the tutorial shows in the code example the variable `bundletoolJarPath` of `AabConvertToUniversalApk@1` is "Optional if you use the InstallBundletool task or set the bundletoolpath environment variable." which it seems to be your case.

Hope you will solve your issue and thanks for reading my tutorials!
